language: python


python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python chang_list_value_inplace.py
script: python check_list_all_elements_equal.py
script: python chinese_value_dict_print.py